patch:
  version: 0.0.1
  relatedImages:
    - name: RELATED_IMAGE_RHAII_CLUSTER_VALIDATOR
      value: "quay.io/opendatahub/odh-rhaii-cluster-validator:latest"
    - name: RELATED_IMAGE_RHAII_VALIDATOR_TOOLS
      value: "quay.io/opendatahub/odh-rhaii-validator-tools:latest"
